theme = "everforest_dark_hc"

[editor]
bufferline = "multiple"
auto-completion = false
auto-format = true
idle-timeout = 200
completion-trigger-len = 3
mouse = false

[editor.file-picker]
hidden = false
git-ignore = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
tab = "→"

[editor.statusline]
left = ["mode", "file-name", "file-modification-indicator", "version-control"]
center = ["spinner", "diagnostics"]
right = ["selections", "position"]

[keys.normal]
# Movement
w = "move_visual_line_up"
W = "goto_prev_paragraph"

s = "move_visual_line_down"
S = "goto_next_paragraph"

a = "move_char_left"
A = "move_prev_word_start"

d = "move_char_right"
D = "move_next_word_start"

# Edit
i = "insert_mode"
o = "append_mode"
I = "insert_at_line_start"
O = "insert_at_line_end"
e = "delete_selection"
E = "delete_char_backward"
C-x = "delete_selection"
t = "select_regex"
f = ["select_all", "select_regex"]

# Navigation
A-q = "workspace_diagnostics_picker"
A-tab = "goto_next_buffer"
S-tab = "rotate_view"
C-down = "copy_selection_on_next_line"
C-up = "copy_selection_on_prev_line"
C-o = "file_picker_in_current_directory"
"C-S-o" = "file_picker"
"C-S-f" = "global_search"
C-d = ":buffer-close"
C-b = "goto_definition"
C-q = "hover"
"§" = "command_palette"
left = "jump_view_left"
right = "jump_view_right"
up = "jump_view_up"
down = "jump_view_down"
"A-ret" = "code_action"

[keys.select]

w = "extend_line_up"
s = "extend_line_down"
a = "extend_char_left"
A = "extend_prev_word_end"
d = "extend_char_right"
D = "extend_next_word_end"

e = "delete_selection"
C-x = "delete_selection"

[keys.insert]
C-b = "goto_definition"
C-q = "hover"
C-space = "completion"
"A-ret" = "code_action"
