theme = "everforest_dark_hc"

[editor]
bufferline = "multiple"
auto-completion = false
auto-format = true
idle-timeout = 200
completion-trigger-len = 3
mouse = false

[editor.file-picker]
hidden = false
git-ignore = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
tab = "→"

[editor.statusline]
left = ["mode", "file-name", "file-modification-indicator", "version-control"]
center = ["spinner", "diagnostics"]
right = ["selections", "position"]

[keys.normal]
#n = "goto_next_diag"
#N = "goto_prev_diag"
A-q = "workspace_diagnostics_picker"
A-tab = "goto_next_buffer"
C-down = "copy_selection_on_next_line"
C-up = "copy_selection_on_prev_line"
C-o = "file_picker_in_current_directory"
"C-S-o" = "file_picker"
"C-S-f" = "global_search"
C-d = ":buffer-close"
C-b = "goto_definition"
C-q = "hover"
"§" = "command_palette"
left = "jump_view_left"
right = "jump_view_right"
up = "jump_view_up"
down = "jump_view_down"

[keys.insert]
C-b = "goto_definition"
C-q = "hover"
C-space = "completion"
