[[language]]
name = "rust"
indent = { tab-width = 4, unit = " " }
language-server = { command = "/home/anton/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rust-analyzer" }
rulers = [100]
auto-format = true

[[language.config]]
checkOnSave = { command = "clippy" }

[[language]]
name = "kotlin"
indent = { tab-width = 4, unit = " " }
rulers = [100, 120]

[[language]]
name = "markdown"
text-width = 100
