[[language]]
name = "rust"
indent = { tab-width = 4, unit = " " }
rulers = [100]
auto-format = true

[language-servers.rust-analyzer]
command = "/home/anton/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rust-analyzer"
config = { check.command = "clippy" }

[[language]]
name = "kotlin"
indent = { tab-width = 4, unit = " " }
rulers = [100, 120]

[[language-servers.kotlin-language-server]]
command = "/home/anton/.bin/kls/server/bin/kotlin-language-server"

[[language]]
name = "markdown"
text-width = 100
